services:
  - type: web
    name: attendance-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: |
      python deployment.py
      gunicorn run:app --worker-class eventlet --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_APP
        value: run.py
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: attendance_db
          property: connectionString

databases:
  - name: attendance_db
    databaseName: attendance
    plan: free
